package views.swing;

import Util.MessageType;
import controllers.AgendaController;
import model.Model;
import org.jetbrains.annotations.NotNull;
import views.AgendaView;

import javax.swing.*;
import java.awt.*;

public class AgendaSwing implements AgendaView {
    private Model model;
    private AgendaController controller;

    private JPanel root;
    private JButton studentsButton;
    private JButton groupsButton;

    public AgendaSwing() {
    }

    @Override
    public void start() {
        JFrame frame = Frame.getIstance().getFrame();
        frame.setContentPane(this.root);
        frame.pack();
    }

    @Override
    public void selectGroup() {

    }

    @Override
    public void setController(@NotNull AgendaController controller) {
        this.controller = controller;
        studentsButton.addActionListener(actionEvent -> controller.startStudents());
        groupsButton.addActionListener(actionEvent -> controller.startGroups());
    }

    @Override
    public void setModel(@NotNull Model model) {
        this.model = model;
    }

    @Override
    public void showMessage(@NotNull String message, @NotNull MessageType type) {

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        root = new JPanel();
        root.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 3, new Insets(0, 0, 0, 0), -1, -1));
        studentsButton = new JButton();
        studentsButton.setText("Students");
        root.add(studentsButton, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        groupsButton = new JButton();
        groupsButton.setText("Groups");
        root.add(groupsButton, new com.intellij.uiDesigner.core.GridConstraints(0, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("Agenda");
        root.add(label1, new com.intellij.uiDesigner.core.GridConstraints(1, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return root;
    }
}
